CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR (50) NOT NULL UNIQUE,
	email VARCHAR (100) NOT NULL,
	password VARCHAR (255) NOT NULL,
	title VARCHAR (50),
	created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	likes_count INTEGER NOT NULL DEFAULT 0
	is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE user_likes (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	post_id INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	liked_at TIMESTAMP DEFAULT NOW(),
	UNIQUE (user_id, post_id)
);
