
-- COMMENTED ALL FOR NOW CAUSE ITS NOT GONNA BE USED ANYMORE

-- LOG USERS
-- SELECT '>>> TABLE "USERS" :' AS log_message;
-- SELECT * FROM users;

-- LOG POSTS
-- SELECT '>>> TABLE "POSTS" :' AS log_message;
-- SELECT * FROM posts;
